version: "2"

services:
  nginx:
    image: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/keys:/etc/nginx/keys
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - outside
      - internal
  editor:
    build:
      context: ./
    ports:
      - "4040:4040"
    networks:
      - internal
  ipfs:
    build:
      context: ./ipfs-node
    ports:
      - "3000:3000"
    networks:
      - internal

networks:
  internal:
    internal: true
  outside:
    driver: bridge
